name: Build Wheels

on:
  push:
    tags: ['v*']
    branches: ['*test*']

jobs:
  build_win:
    if: |
      contains(github.event.head_commit.message, 'pypi test') ||
      startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check gcc
        run: where g++

      - name: Build wheel
        run: g++
